--- # Start

--- # change port
server:
  port: 8085

--- # Thymeleaf
spring:
  thymeleaf:
    cache: false # ?? ?? reload
    prefix: classpath:/templates # classpath:/templates
    suffix: .html

--- # mariadb
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/boot_study
    username: root
    password: 1234

--- #
spring:
  jpa:
    hibernate:
      ddl-auto: none #update
    properties:
      hibernate:
        show_sql : true
        format_sql: true